### ISSUE TITLE
Crash whilst loading - New Update

### ISSUE THREAD

**Issue by pixzi** [T145/metalchests#41]
## Error Details

- Crashes upon trying to load up.
I updated to the new version this morning, the old was working perfectly. I try to load it up and it crashes every time i tried, everything is up to date and everything worked prior to me updating this mod.

[crash-2018-10-02_07.11.38-client.txt](https://github.com/T145/metalchests/files/2436654/crash-2018-10-02_07.11.38-client.txt)

~~ Environment~~

- OS: windows
- Full Forge version: Minecraft 1.12.2 - Forge 14.23.4.2765
- Mod version: V3.5.6

*** Tried without optifine as well, still crashes the same***

**Comment by MasterEnderman** [comment]
https://paste.dimdev.org/jicipeqoko.mccrash

**Comment by T145** [comment]
This should be fixed in the latest release. I tested it in a bare install on both the client and server and it ran perfectly.

**Comment by MasterEnderman** [comment]
https://paste.dimdev.org/xuserazaxu.mccrash still crashes with the new update
